# Generated by Django 5.2.16 on 2026-08-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=200)),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="Opcional. Caminho interno (ex: /ofertas/) ou URL completa. Vazio = banner não é clicável.",
                        max_length=300,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Banners com número menor aparecem primeiro.",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["ordem", "criado_em"],
            },
        ),
    ]
