# Generated by Django 5.2.16 on 2026-08-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="imagem_estatica",
            field=models.CharField(
                blank=True,
                help_text="Caminho dentro de static/, ex: images/banners/inauguracao.jpg. Vazio = mostra só o degradê de fundo, sem foto.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="subtexto",
            field=models.CharField(
                blank=True,
                help_text="Linha menor, opcional, abaixo do título.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="texto",
            field=models.CharField(
                help_text="Título grande, sobre a imagem.", max_length=200
            ),
        ),
    ]
