# Generated by Django 5.2.16 on 2026-08-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0003_banners_iniciais"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="alinhamento",
            field=models.CharField(
                choices=[("esquerda", "Esquerda"), ("direita", "Direita")],
                default="esquerda",
                help_text="De que lado o texto aparece sobre a imagem - escolha o lado onde a foto não tem o assunto principal (rosto, produto), pra não cobrir.",
                max_length=10,
            ),
        ),
    ]
