# Generated by Django 5.2.16 on 2026-08-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0005_inauguracao_texto_direita"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="link",
        ),
        migrations.AddField(
            model_name="banner",
            name="botao2_link",
            field=models.CharField(
                blank=True, help_text="Caminho interno ou URL completa.", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="botao2_texto",
            field=models.CharField(
                blank=True,
                help_text="Texto do botão secundário (contorno, opcional).",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="botao_link",
            field=models.CharField(
                blank=True,
                help_text="Caminho interno (ex: /ofertas/) ou URL completa.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="botao_texto",
            field=models.CharField(
                blank=True,
                help_text="Texto do botão principal. Vazio = sem botão.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="selo",
            field=models.CharField(
                blank=True,
                help_text="Etiqueta pequena acima do título (ex: MÊS DE INAUGURAÇÃO). Opcional.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="alinhamento",
            field=models.CharField(
                choices=[("esquerda", "Esquerda"), ("direita", "Direita")],
                default="esquerda",
                help_text="Só vale quando tem imagem: de que lado o texto aparece sobre a foto - escolha o lado onde a foto não tem o assunto principal (rosto, produto), pra não cobrir.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="imagem_estatica",
            field=models.CharField(
                blank=True,
                help_text="Caminho dentro de static/, ex: images/banners/inauguracao.jpg. Vazio = banner sem foto, com fundo em degradê da marca e texto centralizado.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="texto",
            field=models.CharField(
                help_text="Título grande. Pode usar &lt;mark&gt;palavra&lt;/mark&gt; pra destacar uma palavra com fundo verde-limão (ex: Cashback em &lt;mark&gt;DOBRO&lt;/mark&gt;).",
                max_length=200,
            ),
        ),
    ]
