# Generated by Django 5.2.16 on 2026-08-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0007_atualizar_banners_iniciais"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="botao2_texto",
            field=models.CharField(
                blank=True,
                help_text="Texto do link secundário, sem caixa (opcional).",
                max_length=40,
            ),
        ),
    ]
