# Generated by Django 5.2.16 on 2026-08-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0008_alter_banner_botao2_texto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Banner",
        ),
    ]
