# Generated by Django 5.2.16 on 2026-08-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegistroPublicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(db_index=True, verbose_name="Data de referência"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("story", "Story"), ("feed", "Post no feed")],
                        max_length=10,
                    ),
                ),
                (
                    "conteudo_tipo",
                    models.CharField(
                        choices=[
                            ("oferta_diaria", "Destaque de ofertas do dia"),
                            ("dica", "Dica de economia"),
                            ("lembrete", "Lembrete de cashback"),
                            ("institucional", "Institucional"),
                            ("ofertas_semana", "Melhores ofertas da semana"),
                        ],
                        max_length=20,
                    ),
                ),
                ("legenda", models.TextField(blank=True)),
                ("imagem_url", models.URLField(blank=True)),
                ("instagram_media_id", models.CharField(blank=True, max_length=64)),
                (
                    "modo_simulacao",
                    models.BooleanField(
                        default=True,
                        help_text="True quando o bot ainda estava desligado (INSTAGRAM_BOT_ATIVO=False).",
                    ),
                ),
                ("sucesso", models.BooleanField(default=False)),
                ("erro", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
    ]
