# Generated by Django 5.2.16 on 2026-08-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registropublicacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("simulado", "Simulado (bot desligado)"),
                    ("pendente_aprovacao", "Aguardando aprovação"),
                    ("publicado", "Publicado"),
                    ("rejeitado", "Rejeitado"),
                    ("erro", "Erro"),
                ],
                db_index=True,
                default="simulado",
                max_length=20,
            ),
        ),
    ]
