# Generated by Django 5.2.16 on 2026-08-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_bot", "0002_registropublicacao_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="registropublicacao",
            name="imagem_urls",
            field=models.TextField(
                blank=True,
                help_text="Uma URL por linha - só usado quando é carrossel (várias imagens). Nesse caso imagem_url fica vazio.",
            ),
        ),
    ]
