# Generated by Django 5.2.16 on 2026-08-05 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_bot", "0003_registropublicacao_imagem_urls"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoTokenInstagram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "renovado_em",
                    models.DateField(
                        default=datetime.date.today,
                        help_text='Data em que o INSTAGRAM_ACCESS_TOKEN foi gerado/renovado pela última vez. Atualize sempre que trocar o token no Render (ou use a ação "Marcar token como renovado hoje" aqui no Admin).',
                    ),
                ),
                (
                    "ultimo_lembrete_em",
                    models.DateField(
                        blank=True,
                        help_text="Data do último e-mail de lembrete enviado (evita mandar um por dia).",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
