# Generated by Django 5.2.16 on 2026-08-05 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_bot", "0004_estadotokeninstagram"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estadotokeninstagram",
            options={
                "verbose_name": "Estado do token do Instagram",
                "verbose_name_plural": "Estado do token do Instagram",
            },
        ),
    ]
