# Generated by Django 5.2.16 on 2026-08-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_bot", "0005_alter_estadotokeninstagram_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="registropublicacao",
            name="oferta_categoria_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Só preenchido em stories de oferta - usado pra não repetir categoria no mesmo dia (ver instagram_bot/services.py, publicar_story_oferta_do_momento).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registropublicacao",
            name="oferta_item_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registropublicacao",
            name="oferta_nome",
            field=models.CharField(
                blank=True,
                help_text="Nome do produto no momento da publicação - usado pra não repetir o mesmo produto (vindo de lojas diferentes) no mesmo dia.",
                max_length=255,
            ),
        ),
    ]
