# Generated by Django 5.2.16 on 2026-08-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_bot", "0006_registropublicacao_oferta_categoria_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registropublicacao",
            name="conteudo_tipo",
            field=models.CharField(
                choices=[
                    ("oferta_diaria", "Destaque de ofertas do dia"),
                    ("dica", "Dica de economia"),
                    ("lembrete", "Lembrete de cashback"),
                    ("institucional", "Institucional"),
                    ("ofertas_semana", "Melhores ofertas da semana"),
                    ("combo_diario", "Combo do dia (3 stories)"),
                ],
                max_length=20,
            ),
        ),
    ]
