# Generated by Django 5.2.16 on 2026-09-02 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_bot", "0008_alter_registropublicacao_conteudo_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="registropublicacao",
            name="link_produto_original",
            field=models.URLField(
                blank=True,
                help_text="Link do produto na Shopee (product_link) no momento da publicação - só preenchido em stories de oferta. Guardado aqui (e não só na Oferta) porque o catálogo sincronizado é apagado/recriado todo dia (pk muda) e uma OfertaManual/OfertaDestaqueManual pode ser editada ou removida depois - sem isso, o link enviado por DM quando alguém responde ao story (ver webhook.py) quebraria fora da hora. Ver instagram_bot/views.py, ir_para_story_de_oferta.",
            ),
        ),
        migrations.CreateModel(
            name="RespostaStoryEnviada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instagram_story_media_id",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "sender_instagram_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="ID (IGSID) de quem respondeu",
                    ),
                ),
                ("texto_recebido", models.TextField(blank=True)),
                ("link_enviado", models.URLField(blank=True)),
                ("dm_enviada", models.BooleanField(default=False)),
                ("dm_erro", models.TextField(blank=True)),
                ("payload_bruto", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "registro_publicacao",
                    models.ForeignKey(
                        blank=True,
                        help_text="Story identificado como o respondido - vazio quando não achou (ex: story de fora do calendário de ofertas, ou media_id que não bate com nenhum registro nosso).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="respostas_story",
                        to="instagram_bot.registropublicacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta a story enviada",
                "verbose_name_plural": "Respostas a stories enviadas",
                "ordering": ["-criado_em"],
            },
        ),
    ]
