# Generated by Django 5.2.16 on 2026-09-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_bot", "0009_registropublicacao_link_produto_original_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RespostaStoryEnviada",
        ),
    ]
