# Generated by Django 5.2.16 on 2026-08-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_id",
                    models.BigIntegerField(
                        unique=True, verbose_name="ID do produto na Shopee"
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("imagem_url", models.URLField(blank=True)),
                (
                    "preco_min",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "preco_max",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "percentual_desconto",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Desconto mostrado na Shopee, ex: 10 representa 10%.",
                    ),
                ),
                (
                    "percentual_comissao",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Ex: 0.0500 representa 5%.",
                        max_digits=5,
                    ),
                ),
                (
                    "avaliacao",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("vendas", models.PositiveIntegerField(default=0)),
                (
                    "categoria_id",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="ID da categoria (nível 1)"
                    ),
                ),
                (
                    "categoria_nome",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Nome da categoria (nível 1)",
                    ),
                ),
                ("loja_nome", models.CharField(blank=True, max_length=255)),
                (
                    "product_link",
                    models.URLField(
                        help_text="Convertido em link de afiliado só na hora do clique.",
                        verbose_name="Link original do produto",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-vendas"],
            },
        ),
    ]
