# Generated by Django 5.2.16 on 2026-08-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ofertas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NomeCurtoCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.BigIntegerField(unique=True)),
                ("nome_original", models.CharField(max_length=255)),
                ("nome_curto", models.CharField(max_length=255)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="oferta",
            name="nome_curto",
            field=models.CharField(
                blank=True,
                help_text="Versão enxuta do nome (via Gemini) pra exibição - ver ofertas/gemini_client.py. Sempre preenchido (cai pro nome original se o Gemini não estiver configurado/disponível).",
                max_length=255,
            ),
        ),
    ]
