# Generated by Django 5.2.16 on 2026-08-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ofertas", "0002_nomecurtocache_oferta_nome_curto"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaixaCashbackCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentual_minimo",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "percentual_maximo",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
