# Generated by Django 5.2.16 on 2026-08-29 12:44

import ofertas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ofertas", "0005_ofertamanual"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfertaDestaqueManual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_link",
                    models.URLField(verbose_name="Link do produto na Shopee"),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "imagem_url",
                    models.URLField(verbose_name="URL da imagem do produto"),
                ),
                (
                    "preco_antigo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preço original, exibido riscado.",
                        max_digits=10,
                        verbose_name="Preço antigo",
                    ),
                ),
                (
                    "preco_novo",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço novo"
                    ),
                ),
                (
                    "preco_avista",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ex: preço no Pix/boleto, se for menor que o preço novo. Opcional - usado como base do cashback quando preenchido (senão usa o preço novo).",
                        max_digits=10,
                        null=True,
                        verbose_name="Preço à vista (com desconto)",
                    ),
                ),
                (
                    "percentual_desconto",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Desconto mostrado no selo, ex: 10 representa 10%.",
                        verbose_name="% de desconto",
                    ),
                ),
                (
                    "percentual_comissao",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="% de comissão desse produto (ex: 0.0500 representa 5%) - confira no seu extrato de afiliado ou no app da Shopee. O % de cashback exibido é calculado a partir daqui, igual às ofertas sincronizadas.",
                        max_digits=5,
                        verbose_name="% de comissão",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Oferta do dia (destaque manual)",
                "verbose_name_plural": "Oferta do dia (destaque manual)",
            },
            bases=(ofertas.models._CashbackEstimadoMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="ofertamanual",
            name="percentual_desconto",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Desconto mostrado no selo, ex: 10 representa 10%.",
                verbose_name="% de desconto",
            ),
        ),
    ]
