# Generated by Django 5.2.16 on 2026-09-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ofertas", "0006_ofertadestaquemanual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ofertadestaquemanual",
            name="preco_antigo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Preço original, exibido riscado. Opcional - deixe em branco quando a loja não mostrar um preço "de" pra esse produto.',
                max_digits=10,
                null=True,
                verbose_name="Preço antigo",
            ),
        ),
        migrations.AlterField(
            model_name="ofertamanual",
            name="preco_antigo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Preço original, exibido riscado. Opcional - deixe em branco quando a loja não mostrar um preço "de" pra esse produto.',
                max_digits=10,
                null=True,
                verbose_name="Preço antigo",
            ),
        ),
    ]
