# Generated by Django 5.2.16 on 2026-07-30 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Saque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "chave_pix",
                    models.CharField(
                        help_text="Cópia da chave PIX do usuário no momento da solicitação.",
                        max_length=140,
                    ),
                ),
                ("tipo_chave_pix", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("solicitado", "Solicitado"),
                            ("processando", "Processando"),
                            ("pago", "Pago"),
                            ("falhou", "Falhou"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="solicitado",
                        max_length=12,
                    ),
                ),
                ("asaas_transfer_id", models.CharField(blank=True, max_length=64)),
                (
                    "resposta_asaas",
                    models.TextField(
                        blank=True,
                        help_text="Resposta (ou erro) bruta da Asaas, guardada para conferência.",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("pago_em", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saques",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
    ]
