# Generated by Django 5.2.16 on 2026-08-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saques", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saque",
            name="inter_codigo_solicitacao",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="saque",
            name="provedor",
            field=models.CharField(
                blank=True,
                choices=[("asaas", "Asaas"), ("inter", "Inter")],
                help_text="Qual provedor pagou (ou tentou pagar) este saque - definido na hora da aprovação manual.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="saque",
            name="resposta_inter",
            field=models.TextField(
                blank=True,
                help_text="Resposta (ou erro) bruta do Inter, guardada para conferência.",
            ),
        ),
    ]
