# Generated by Django 5.2.16 on 2026-09-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saques", "0002_saque_inter_codigo_solicitacao_saque_provedor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saque",
            name="chave_pix",
            field=models.CharField(
                help_text="Cópia da chave Pix do usuário no momento da solicitação.",
                max_length=140,
            ),
        ),
    ]
