# Generated by Django 5.2.16 on 2026-07-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="data_liberacao",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento em que o comando liberar_saldo efetivamente liberou este pedido.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="data_prevista_liberacao",
            field=models.DateField(
                blank=True,
                help_text="1º dia do mês em que o saldo deste pedido fica liberado (mês da validação + 2).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("validado", "Validado"),
                    ("liberado", "Liberado"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendente",
                max_length=10,
            ),
        ),
    ]
