# Generated by Django 5.2.16 on 2026-07-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pedidos",
            "0002_pedido_data_liberacao_pedido_data_prevista_liberacao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="motivo_cancelamento",
            field=models.CharField(
                blank=True,
                help_text="Motivo informado pela Shopee (fraudReason), quando cancelado.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="produto_imagem_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="produto_nome",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
