# Generated by Django 5.2.16 on 2026-08-18 12:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pedidos",
            "0003_pedido_motivo_cancelamento_pedido_produto_imagem_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="multiplicador_campanha",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1"),
                help_text="Multiplicador de campanha (CASHBACK_MULTIPLICADOR_CAMPANHA) que valia quando este pedido foi registrado pela primeira vez. Fica congelado aqui de propósito: a Shopee reenvia o mesmo pedido em toda sincronização seguinte, e sem isso o cashback seria recalculado com o multiplicador vigente naquele momento - o dobro prometido numa campanha sumiria assim que ela acabasse. Ver pedidos/services.py::sincronizar.",
                max_digits=4,
            ),
        ),
    ]
