# Generated by Django 5.2.16 on 2026-08-22 19:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0004_pedido_multiplicador_campanha"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="valor_pedido",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Valor realmente pago pelo comprador (actualAmount da Shopee, já descontando cupom/desconto).",
                max_digits=10,
            ),
        ),
    ]
