# Generated by Django 5.2.16 on 2026-09-01 21:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_pedido_valor_pedido"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampanhaCashback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "multiplicador",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2"),
                        help_text="Ex: 2 = cashback em dobro durante essa janela.",
                        max_digits=4,
                        verbose_name="Multiplicador",
                    ),
                ),
                ("inicio", models.DateTimeField(verbose_name="Início")),
                (
                    "fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deixe em branco se ainda não sabe quando a campanha termina.",
                        null=True,
                        verbose_name="Fim",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Campanha de cashback",
                "verbose_name_plural": "Campanhas de cashback",
                "ordering": ["-inicio"],
            },
        ),
    ]
