# Generated by Django 5.2.16 on 2026-09-01 21:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0006_campanhacashback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="multiplicador_campanha",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1"),
                help_text="Multiplicador de CampanhaCashback que valia na data_compra deste pedido, carimbado aqui quando ele foi registrado pela primeira vez. Fica congelado de propósito: a Shopee reenvia o mesmo pedido em toda sincronização seguinte, e sem isso o cashback seria recalculado com o multiplicador vigente naquele momento - o dobro prometido numa campanha sumiria assim que ela acabasse. Ver pedidos/services.py::sincronizar.",
                max_digits=4,
            ),
        ),
    ]
