# Generated by Django 5.2.16 on 2026-07-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chave_pix",
            field=models.CharField(
                blank=True, max_length=140, verbose_name="Chave PIX"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tipo_chave_pix",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CPF", "CPF"),
                    ("CNPJ", "CNPJ"),
                    ("EMAIL", "E-mail"),
                    ("PHONE", "Telefone"),
                    ("EVP", "Chave aleatória"),
                ],
                max_length=10,
                verbose_name="Tipo da chave PIX",
            ),
        ),
    ]
