# Generated by Django 5.2.16 on 2026-08-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_chave_pix_user_tipo_chave_pix"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verificado",
            field=models.BooleanField(default=False, verbose_name="E-mail verificado"),
        ),
    ]
