# Generated by Django 5.2.16 on 2026-08-13 00:14

import secrets

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

ALFABETO_CODIGO_INDICACAO = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
TAMANHO_CODIGO_INDICACAO = 8


def gerar_codigos_para_usuarios_existentes(apps, schema_editor):
    """codigo_indicacao é único - contas criadas antes deste recurso existir
    ficariam todas com "" e quebrariam a constraint assim que a segunda salvasse."""
    User = apps.get_model("accounts", "User")
    codigos_em_uso = set(User.objects.exclude(codigo_indicacao="").values_list("codigo_indicacao", flat=True))
    for usuario in User.objects.filter(codigo_indicacao=""):
        while True:
            codigo = "".join(secrets.choice(ALFABETO_CODIGO_INDICACAO) for _ in range(TAMANHO_CODIGO_INDICACAO))
            if codigo not in codigos_em_uso:
                codigos_em_uso.add(codigo)
                break
        usuario.codigo_indicacao = codigo
        usuario.save(update_fields=["codigo_indicacao"])


def reverter(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_verificar_usuarios_existentes"),
        (
            "pedidos",
            "0003_pedido_motivo_cancelamento_pedido_produto_imagem_url_and_more",
        ),
    ]

    operations = [
        # Sem unique=True ainda - com usuários já existentes, todos ganhariam o
        # mesmo valor em branco ao mesmo tempo nessa etapa, e o UNIQUE quebraria
        # antes mesmo do RunPython abaixo ter a chance de gerar códigos distintos.
        migrations.AddField(
            model_name="user",
            name="codigo_indicacao",
            field=models.CharField(
                blank=True,
                max_length=8,
                default="",
                verbose_name="Código de indicação",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Indicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "indicado",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicacao_recebida",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "indicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicacoes_feitas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pedido_bonus_indicado",
                    models.ForeignKey(
                        blank=True,
                        help_text="1ª compra validada do indicado - dispara o cashback em dobro dela.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "pedido_bonus_indicador",
                    models.ForeignKey(
                        blank=True,
                        help_text="Próxima compra validada de quem indicou depois do bônus acima - cashback em dobro dela.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pedidos.pedido",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.RunPython(gerar_codigos_para_usuarios_existentes, reverter),
        # Só agora, com todo mundo já tendo um código distinto, é seguro exigir
        # unicidade no banco.
        migrations.AlterField(
            model_name="user",
            name="codigo_indicacao",
            field=models.CharField(
                blank=True,
                max_length=8,
                unique=True,
                verbose_name="Código de indicação",
            ),
        ),
    ]
