# Generated by Django 5.2.16 on 2026-08-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_codigo_indicacao_indicacao"),
    ]

    def criar_linha_unica(apps, schema_editor):
        ConfiguracaoIndicacao = apps.get_model("accounts", "ConfiguracaoIndicacao")
        ConfiguracaoIndicacao.objects.get_or_create(pk=1, defaults={"ativa": True})

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoIndicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(default=True, verbose_name="Campanha ativa"),
                ),
            ],
            options={
                "verbose_name": "Configuração de indicação",
                "verbose_name_plural": "Configuração de indicação",
            },
        ),
        migrations.RunPython(criar_linha_unica, migrations.RunPython.noop),
    ]
