# Generated by Django 5.2.16 on 2026-09-23 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_chave_pix_alter_user_tipo_chave_pix"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComunicacaoEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assunto", models.CharField(max_length=200, verbose_name="Assunto")),
                (
                    "corpo",
                    models.TextField(
                        help_text="Texto simples, sem HTML.",
                        verbose_name="Corpo do e-mail",
                    ),
                ),
                (
                    "filtro",
                    models.CharField(
                        choices=[
                            ("todos", "Todos os usuários cadastrados"),
                            ("com_pedidos", "Já fizeram pelo menos 1 pedido"),
                            ("sem_pedidos", "Ainda não fizeram nenhum pedido"),
                            ("email_verificado", "E-mail verificado"),
                            ("email_nao_verificado", "E-mail ainda não verificado"),
                            ("ja_sacou", "Já sacaram pelo menos uma vez"),
                            ("nunca_sacou", "Nunca sacaram"),
                        ],
                        max_length=30,
                        verbose_name="Filtro de destinatários",
                    ),
                ),
                (
                    "total_destinatarios",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de destinatários"
                    ),
                ),
                (
                    "total_enviados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total enviados com sucesso"
                    ),
                ),
                (
                    "enviado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comunicação por e-mail",
                "verbose_name_plural": "Comunicações por e-mail",
                "ordering": ["-enviado_em"],
            },
        ),
    ]
