# Generated by Django 5.2.16 on 2026-09-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_comunicacaoemail"),
        ("ofertas", "0007_alter_ofertadestaquemanual_preco_antigo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunicacaoemail",
            name="corpo_html",
            field=models.TextField(
                blank=True,
                help_text="Gerado automaticamente a partir do corpo em texto + ofertas escolhidas - guardado aqui pra manter fiel o que foi realmente mandado, mesmo que preço/imagem da oferta mude depois.",
                verbose_name="Corpo em HTML (com a vitrine)",
            ),
        ),
        migrations.AddField(
            model_name="comunicacaoemail",
            name="ofertas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Vitrine de produtos incluída no e-mail (imagem + link de cashback de cada uma).",
                related_name="+",
                to="ofertas.oferta",
                verbose_name="Ofertas em destaque",
            ),
        ),
    ]
