# Generated by Django 5.2.16 on 2026-09-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_comunicacaoemail_corpo_html_comunicacaoemail_ofertas"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunicacaoemail",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("anuncio", "Anúncio/promoção"),
                    ("geral", "Comunicação geral"),
                ],
                default="anuncio",
                help_text="Anúncio/promoção respeita quem desligou e-mail de marketing e inclui o link de descadastro. Comunicação geral vai pra todo mundo do filtro, sem esse link.",
                max_length=10,
                verbose_name="Tipo",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="aceita_email_marketing",
            field=models.BooleanField(
                default=True,
                help_text='Desligado quando a pessoa clica em "não quero mais receber" num anúncio. Não afeta e-mails transacionais (verificação, senha, avisos de saque) nem comunicações gerais.',
                verbose_name="Aceita e-mails de promoções/anúncios",
            ),
        ),
    ]
