# Generated by Django 5.2.16 on 2026-09-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_comunicacaoemail_tipo_user_aceita_email_marketing"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunicacaoemail",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Aparece no topo do e-mail, antes do texto - ex: banner de campanha/promoção.",
                null=True,
                upload_to="comunicacoes/banners/",
                verbose_name="Imagem de banner (opcional)",
            ),
        ),
    ]
