# Generated by Django 5.2.16 on 2026-09-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_comunicacaoemail_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="origem_cadastro",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="utm_source da primeira visita (ex: pinterest, instagram).",
                max_length=50,
                verbose_name="Origem do cadastro",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="origem_campanha",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Campanha de origem"
            ),
        ),
    ]
