"""
Django settings for cashback_shopee project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from decimal import Decimal
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-!txnn&9z%j3hvt)hv(o4@_%@8&_1pq2zzpl+#9b4352e66koh3",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h]

# A Render injeta esse valor automaticamente com o endereço público do serviço
# (ex: seusite.onrender.com) - assim não precisamos configurar isso manualmente.
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS]

# A Render fica na frente do site fazendo HTTPS -> HTTP internamente; esse cabeçalho
# avisa o Django que a conexão original do usuário era HTTPS.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Começa com 1 hora (valor conservador); pode aumentar depois de confirmar que o
    # HTTPS está estável, seguindo a documentação do Django antes de mudar.
    SECURE_HSTS_SECONDS = 3600


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "accounts",
    "links",
    "pedidos",
    "saques",
    "paginas",
    "ofertas",
    "instagram_bot",
]

AUTH_USER_MODEL = "accounts.User"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"

# Credenciais da API oficial de afiliados da Shopee (ficam no arquivo .env, nunca no código)
SHOPEE_AFFILIATE_APP_ID = os.environ.get("SHOPEE_AFFILIATE_APP_ID", "")
SHOPEE_AFFILIATE_SECRET = os.environ.get("SHOPEE_AFFILIATE_SECRET", "")
SHOPEE_AFFILIATE_API_URL = os.environ.get(
    "SHOPEE_AFFILIATE_API_URL", "https://open-api.affiliate.shopee.com.br/graphql"
)
SHOPEE_HOME_URL = os.environ.get("SHOPEE_HOME_URL", "https://shopee.com.br/")

# Percentual da comissão da Shopee repassado ao usuário como cashback.
# Ainda não definido pelo negócio - ajuste no .env quando decidido (ex: 100 = repassa tudo).
SHOPEE_CASHBACK_PERCENTUAL = float(os.environ.get("SHOPEE_CASHBACK_PERCENTUAL", "100"))

# Credenciais da API da Asaas para pagar os saques via PIX (ficam no arquivo .env, nunca no código)
ASAAS_API_KEY = os.environ.get("ASAAS_API_KEY", "")
ASAAS_API_URL = os.environ.get("ASAAS_API_URL", "https://sandbox.asaas.com/api/v3")

# Credenciais da API Banking do Inter, alternativa à Asaas pra pagar saques via PIX
# (Internet Banking > Soluções para sua empresa > Nova integração). Autenticação é
# OAuth2 + certificado mTLS (não só uma chave de API) - os arquivos de certificado
# baixados no Internet Banking ficam fora do repositório (ver .gitignore) e o caminho
# deles no disco é o que entra aqui.
INTER_CLIENT_ID = os.environ.get("INTER_CLIENT_ID", "")
INTER_CLIENT_SECRET = os.environ.get("INTER_CLIENT_SECRET", "")
INTER_CERT_PATH = os.environ.get("INTER_CERT_PATH", "")
INTER_KEY_PATH = os.environ.get("INTER_KEY_PATH", "")
# Só precisa preencher se a aplicação estiver associada a mais de uma conta corrente.
INTER_CONTA_CORRENTE = os.environ.get("INTER_CONTA_CORRENTE", "")
INTER_API_URL = os.environ.get("INTER_API_URL", "https://cdpj-sandbox.partners.uatinter.co")

# Valor mínimo (em reais) que o usuário precisa ter de saldo liberado para poder solicitar saque.
SAQUE_VALOR_MINIMO = Decimal(os.environ.get("SAQUE_VALOR_MINIMO", "20.00"))

# Senha (token) que protege o endereço /tarefas/executar/, usado pelo agendamento
# automático (GitHub Actions) para rodar as tarefas diárias em produção. Sem essa
# variável configurada, o endereço fica sempre bloqueado.
TAREFAS_TOKEN = os.environ.get("TAREFAS_TOKEN", "")

# Credenciais do bot do Instagram (Instagram API com Login do Instagram - não usa
# Página do Facebook). Ficam no .env / variáveis de ambiente do Render, nunca no
# código. Ver marketing/instagram/README.md para o histórico completo da configuração.
INSTAGRAM_APP_ID = os.environ.get("INSTAGRAM_APP_ID", "")
INSTAGRAM_APP_SECRET = os.environ.get("INSTAGRAM_APP_SECRET", "")
INSTAGRAM_ACCESS_TOKEN = os.environ.get("INSTAGRAM_ACCESS_TOKEN", "")
INSTAGRAM_BUSINESS_ACCOUNT_ID = os.environ.get("INSTAGRAM_BUSINESS_ACCOUNT_ID", "")
INSTAGRAM_GRAPH_API_URL = os.environ.get("INSTAGRAM_GRAPH_API_URL", "https://graph.instagram.com")

# Interruptor mestre do bot: enquanto False, o bot gera o conteúdo do dia e
# registra tudo (RegistroPublicacao) mas NÃO publica de verdade no Instagram
# (modo "dry-run"). Vira True só quando o perfil já estiver semeado manualmente
# com os posts institucionais iniciais (ver marketing/instagram/README.md).
INSTAGRAM_BOT_ATIVO = os.environ.get("INSTAGRAM_BOT_ATIVO", "False") == "True"

# Só importa quando INSTAGRAM_BOT_ATIVO=True. Se True, o bot gera a arte e manda um
# e-mail de aprovação pro INSTAGRAM_APROVADOR_EMAIL em vez de publicar direto -
# só publica depois de clicar em "aprovar" no e-mail. Se False, publica direto.
INSTAGRAM_REQUER_APROVACAO = os.environ.get("INSTAGRAM_REQUER_APROVACAO", "True") == "True"
INSTAGRAM_APROVADOR_EMAIL = os.environ.get("INSTAGRAM_APROVADOR_EMAIL", "contato@cash-b.com")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cashback_shopee.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cashback_shopee.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Imagens geradas pelo bot do Instagram precisam de uma URL pública (a API do
# Instagram busca a imagem ela mesma a partir dessa URL, não aceita upload direto).
# Disco da Render é efêmero, mas isso não é problema aqui: a imagem só precisa
# existir o suficiente pro Instagram buscar logo depois de gerada.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# E-mail (usado para o link de "esqueceu sua senha")
# O Render bloqueia conexões SMTP de saída, então o envio usa a API HTTP do
# Brevo (veja cashback_shopee/brevo_email_backend.py) em vez de SMTP. Sem
# BREVO_API_KEY configurada, os e-mails só aparecem no terminal (backend de
# console) - útil em desenvolvimento local.

BREVO_API_KEY = os.environ.get("BREVO_API_KEY", "")
EMAIL_BACKEND = (
    "cashback_shopee.brevo_email_backend.BrevoAPIEmailBackend"
    if BREVO_API_KEY
    else "django.core.mail.backends.console.EmailBackend"
)
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "cash-b <contato@cash-b.com>")

# Por padrão, o Django só manda os próprios logs de erro (ex: falha ao enviar
# e-mail de redefinição de senha) pro console quando DEBUG=True - em produção
# eles ficam invisíveis. Isso garante que sempre apareçam nos logs do Render.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
