"""
Django settings for cashback_shopee project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from decimal import Decimal
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-!txnn&9z%j3hvt)hv(o4@_%@8&_1pq2zzpl+#9b4352e66koh3",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h]

# A Render injeta esse valor automaticamente com o endereço público do serviço
# (ex: seusite.onrender.com) - assim não precisamos configurar isso manualmente.
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS]

# A Render fica na frente do site fazendo HTTPS -> HTTP internamente; esse cabeçalho
# avisa o Django que a conexão original do usuário era HTTPS.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Começa com 1 hora (valor conservador); pode aumentar depois de confirmar que o
    # HTTPS está estável, seguindo a documentação do Django antes de mudar.
    SECURE_HSTS_SECONDS = 3600


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "accounts",
    "links",
    "pedidos",
    "saques",
    "paginas",
    "ofertas",
    "instagram_bot",
    "automacao_instagram",
    "axes",
]

AUTH_USER_MODEL = "accounts.User"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"

# django-axes: bloqueia tentativas de login por força bruta. AxesBackend precisa vir
# ANTES do ModelBackend padrão (ele intercepta a autenticação pra checar o bloqueio
# antes de validar a senha de verdade).
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Trava por par (usuário, IP) - não usuário sozinho, pra um atacante não conseguir
# bloquear a conta de outra pessoa de propósito só errando a senha dela várias vezes
# de um IP diferente (negação de serviço via bloqueio).
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # horas até o bloqueio expirar sozinho
AXES_RESET_ON_SUCCESS = True
# Página com a identidade visual do site em vez da resposta padrão em texto puro/inglês
# do django-axes. O texto "cerca de 1 hora" nela é fixo, então se AXES_COOLOFF_TIME
# mudar, atualizar o texto junto (accounts/templates/accounts/login_bloqueado.html).
AXES_LOCKOUT_TEMPLATE = "accounts/login_bloqueado.html"

# Credenciais da API oficial de afiliados da Shopee (ficam no arquivo .env, nunca no código)
SHOPEE_AFFILIATE_APP_ID = os.environ.get("SHOPEE_AFFILIATE_APP_ID", "")
SHOPEE_AFFILIATE_SECRET = os.environ.get("SHOPEE_AFFILIATE_SECRET", "")
SHOPEE_AFFILIATE_API_URL = os.environ.get(
    "SHOPEE_AFFILIATE_API_URL", "https://open-api.affiliate.shopee.com.br/graphql"
)
SHOPEE_HOME_URL = os.environ.get("SHOPEE_HOME_URL", "https://shopee.com.br/")

# Percentual da comissão da Shopee repassado ao usuário como cashback.
# Ainda não definido pelo negócio - ajuste no .env quando decidido (ex: 100 = repassa tudo).
SHOPEE_CASHBACK_PERCENTUAL = float(os.environ.get("SHOPEE_CASHBACK_PERCENTUAL", "100"))

# Percentual de comissão que a Shopee paga pra vendas diretas, sem contar o bônus de
# campanha do vendedor (esse é instável e por produto - não entra na conta do hero).
# A Shopee reajusta esse valor todo mês (hoje a faixa é 8% a 10%) - atualize aqui com o
# piso do mês pra nunca prometer mais cashback do que a gente de fato vai conseguir pagar.
SHOPEE_COMISSAO_VENDA_DIRETA = float(os.environ.get("SHOPEE_COMISSAO_VENDA_DIRETA", "8"))

# Multiplicador pra campanhas promocionais próprias da cash-b (não tem nada a ver com
# bônus de vendedor da Shopee) - ex: 2 = "cashback em dobro" no mês de aniversário do
# site. Fica em 1 o resto do tempo. Afeta o valor de cashback pago de verdade (não é só
# um número de propaganda) - usado em pedidos/services.py, ofertas/models.py e no hero.
#
# Vale só pros pedidos registrados ENQUANTO a campanha está ligada: cada Pedido guarda
# o multiplicador que valia quando entrou (campo multiplicador_campanha) e continua com
# ele pra sempre. Ou seja, desligar a campanha não tira o dobro de quem comprou durante
# ela, e ligar não dobra retroativamente quem comprou antes.
CASHBACK_MULTIPLICADOR_CAMPANHA = float(os.environ.get("CASHBACK_MULTIPLICADOR_CAMPANHA", "1"))

# Fallback do "até X%" anunciado no hero da home, só usado antes da primeira
# sincronização de ofertas (instalação nova, ainda sem CashbackMaximoCache calculado -
# ver ofertas/services.py::obter_cashback_maximo_anunciado). Em uso normal, a home
# mostra o maior % real calculado a partir do catálogo sincronizado, não esse valor fixo.
CASHBACK_MAXIMO_ANUNCIADO = round(
    SHOPEE_CASHBACK_PERCENTUAL / 100 * SHOPEE_COMISSAO_VENDA_DIRETA * CASHBACK_MULTIPLICADOR_CAMPANHA, 2
)

# Teto de cashback em R$ por produto (não por pedido - um pedido com vários produtos
# pode ter o teto aplicado várias vezes, um por item). Existe porque agora contamos a
# comissão extra de campanha do vendedor no cálculo (ver SHOPEE_COMISSAO_VENDA_DIRETA
# acima e links/shopee_client.py) - sem um teto, um produto com comissão de campanha
# muito alta pagaria um cashback desproporcional ao preço. Usado em pedidos/services.py
# (valor pago de verdade) e ofertas/models.py (estimativa mostrada no site).
CASHBACK_MAXIMO_POR_PRODUTO = float(os.environ.get("CASHBACK_MAXIMO_POR_PRODUTO", "10"))

# Multiplicador do programa "indique e ganhe": aplicado só ao pedido que dispara o
# bônus (1ª compra validada do indicado, e a compra seguinte de quem indicou) - não é
# um valor fixo em R$, dobra o cashback daquele pedido específico. Ver
# pedidos/services.py (_selecionar_bonus_indicacao).
CASHBACK_MULTIPLICADOR_INDICACAO = float(os.environ.get("CASHBACK_MULTIPLICADOR_INDICACAO", "2"))

# API do Gemini, usada só pra encurtar o nome dos produtos exibidos na aba Ofertas (os
# títulos que vêm da Shopee costumam ser bem longos/cheios de palavra-chave repetida).
# Sem GEMINI_API_KEY configurada, o site continua funcionando normal - só usa o nome
# original sem encurtar (ver ofertas/gemini_client.py e ofertas/services.py).
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
GEMINI_API_URL = os.environ.get("GEMINI_API_URL", "https://generativelanguage.googleapis.com/v1beta")
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-3.1-flash-lite")

# Credenciais da API da Asaas para pagar os saques via PIX (ficam no arquivo .env, nunca no código)
ASAAS_API_KEY = os.environ.get("ASAAS_API_KEY", "")
ASAAS_API_URL = os.environ.get("ASAAS_API_URL", "https://sandbox.asaas.com/api/v3")

# Token do mecanismo de segurança "webhook de validação de transferência" da Asaas,
# usado como alternativa ao código por SMS pra autorizar as transferências PIX dos saques.
# Configurado em Menu do usuário > Integrações > Mecanismos de segurança, na conta Asaas
# (a URL do endpoint é /saques/webhook/validacao/, ver saques/urls.py). O mesmo token
# preenchido lá tem que estar aqui, pra validar o header "asaas-access-token" recebido.
ASAAS_WEBHOOK_TOKEN = os.environ.get("ASAAS_WEBHOOK_TOKEN", "")

# Credenciais da API Banking do Inter, alternativa à Asaas pra pagar saques via PIX
# (Internet Banking > Soluções para sua empresa > Nova integração). Autenticação é
# OAuth2 + certificado mTLS (não só uma chave de API) - os arquivos de certificado
# baixados no Internet Banking ficam fora do repositório (ver .gitignore) e o caminho
# deles no disco é o que entra aqui.
#
# EM PAUSA por enquanto: conta MEI não tem acesso a "Soluções para sua empresa" nem
# pode abrir conta PJ - só dá pra usar isso depois de migrar de MEI pra Simples
# Nacional. Até lá, fica sem preencher e o botão "Aprovar e pagar via PIX (Inter)" no
# Admin sempre falha com InterConfigError (de propósito - sem risco de tentar pagar
# de verdade sem credencial). A Asaas continua sendo o único provedor em uso de fato.
INTER_CLIENT_ID = os.environ.get("INTER_CLIENT_ID", "")
INTER_CLIENT_SECRET = os.environ.get("INTER_CLIENT_SECRET", "")
INTER_CERT_PATH = os.environ.get("INTER_CERT_PATH", "")
INTER_KEY_PATH = os.environ.get("INTER_KEY_PATH", "")
# Só precisa preencher se a aplicação estiver associada a mais de uma conta corrente.
INTER_CONTA_CORRENTE = os.environ.get("INTER_CONTA_CORRENTE", "")
INTER_API_URL = os.environ.get("INTER_API_URL", "https://cdpj-sandbox.partners.uatinter.co")

# Valor mínimo (em reais) que o usuário precisa ter de saldo liberado para poder solicitar saque.
SAQUE_VALOR_MINIMO = Decimal(os.environ.get("SAQUE_VALOR_MINIMO", "20.00"))

# Senha (token) que protege o endereço /tarefas/executar/, usado pelo agendamento
# automático (GitHub Actions) para rodar as tarefas diárias em produção. Sem essa
# variável configurada, o endereço fica sempre bloqueado.
TAREFAS_TOKEN = os.environ.get("TAREFAS_TOKEN", "")

# Credenciais do bot do Instagram (Instagram API com Login do Instagram - não usa
# Página do Facebook). Ficam no .env / variáveis de ambiente do Render, nunca no
# código. Ver marketing/instagram/README.md para o histórico completo da configuração.
INSTAGRAM_APP_ID = os.environ.get("INSTAGRAM_APP_ID", "")
INSTAGRAM_APP_SECRET = os.environ.get("INSTAGRAM_APP_SECRET", "")
INSTAGRAM_ACCESS_TOKEN = os.environ.get("INSTAGRAM_ACCESS_TOKEN", "")
INSTAGRAM_BUSINESS_ACCOUNT_ID = os.environ.get("INSTAGRAM_BUSINESS_ACCOUNT_ID", "")
INSTAGRAM_GRAPH_API_URL = os.environ.get("INSTAGRAM_GRAPH_API_URL", "https://graph.instagram.com")

# Interruptor mestre do bot: enquanto False, o bot gera o conteúdo do dia e
# registra tudo (RegistroPublicacao) mas NÃO publica de verdade no Instagram
# (modo "dry-run"). Vira True só quando o perfil já estiver semeado manualmente
# com os posts institucionais iniciais (ver marketing/instagram/README.md).
INSTAGRAM_BOT_ATIVO = os.environ.get("INSTAGRAM_BOT_ATIVO", "False") == "True"

# Só importa quando INSTAGRAM_BOT_ATIVO=True. Se True, o bot gera a arte e manda um
# e-mail de aprovação pro INSTAGRAM_APROVADOR_EMAIL em vez de publicar direto -
# só publica depois de clicar em "aprovar" no e-mail. Se False, publica direto.
INSTAGRAM_REQUER_APROVACAO = os.environ.get("INSTAGRAM_REQUER_APROVACAO", "True") == "True"
INSTAGRAM_APROVADOR_EMAIL = os.environ.get("INSTAGRAM_APROVADOR_EMAIL", "contato@cash-b.com")

# App automacao_instagram: responde/envia DM em comentários com palavra-chave. Cada
# conta conectada tem seu próprio token (guardado no banco, não aqui - ver
# ContaInstagramConectada), então esse valor só controla o intervalo do worker
# (rodado à parte, como Background Worker no Render - ver
# automacao_instagram/management/commands/automacao_instagram_worker.py).
AUTOMACAO_INSTAGRAM_INTERVALO_SEGUNDOS = int(os.environ.get("AUTOMACAO_INSTAGRAM_INTERVALO_SEGUNDOS", "30"))

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",  # precisa ser o último da lista (exigência do django-axes)
]

ROOT_URLCONF = "cashback_shopee.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cashback_shopee.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Imagens geradas pelo bot do Instagram precisam de uma URL pública (a API do
# Instagram busca a imagem ela mesma a partir dessa URL, não aceita upload direto).
# MEDIA_ROOT é configurável via variável de ambiente pra apontar pro disco persistente
# do Render (Disk) quando ele existir - o disco precisa ser montado FORA da pasta do
# código-fonte (ex: /var/data), então isso é diferente do caminho padrão do projeto.
# Sem a variável configurada, cai no comportamento antigo (pasta "media" dentro do
# próprio projeto - funciona, mas não persiste entre deploys/reinícios sem disco).
#
# O "or" cobre a variável DEFINIDA E VAZIA, que é como o .env.example a distribui:
# os.environ.get devolve "" nesse caso (não o padrão), Path("") vira Path(".") e a
# mídia passa a ser gravada na RAIZ do projeto - fora da pasta "media/", que é a que
# o .gitignore cobre. O resultado é imagem gerada pelo bot aparecendo como arquivo
# novo do repositório.
MEDIA_URL = "media/"
MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT") or BASE_DIR / "media")

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# E-mail (usado para o link de "esqueceu sua senha")
# O Render bloqueia conexões SMTP de saída, então o envio usa a API HTTP do
# Brevo (veja cashback_shopee/brevo_email_backend.py) em vez de SMTP. Sem
# BREVO_API_KEY configurada, os e-mails só aparecem no terminal (backend de
# console) - útil em desenvolvimento local.

BREVO_API_KEY = os.environ.get("BREVO_API_KEY", "")
EMAIL_BACKEND = (
    "cashback_shopee.brevo_email_backend.BrevoAPIEmailBackend"
    if BREVO_API_KEY
    else "django.core.mail.backends.console.EmailBackend"
)
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "cash-b <contato@cash-b.com>")

# Notificações push do PWA (Web Push/VAPID). Sem as duas chaves configuradas, o botão
# "Ativar notificações" no painel some e nenhum push é enviado - só os e-mails de
# sempre continuam funcionando. Gerar um par novo com:
#   python -c "from py_vapid import Vapid02; v = Vapid02(); v.generate_keys(); ..."
# (ver accounts/push.py para o helper completo de geração).
VAPID_PUBLIC_KEY = os.environ.get("VAPID_PUBLIC_KEY", "")
VAPID_PRIVATE_KEY = os.environ.get("VAPID_PRIVATE_KEY", "")
VAPID_CLAIMS_EMAIL = os.environ.get("VAPID_CLAIMS_EMAIL", "contato@cash-b.com")

# Por padrão, o Django só manda os próprios logs de erro (ex: falha ao enviar
# e-mail de redefinição de senha) pro console quando DEBUG=True - em produção
# eles ficam invisíveis. Isso garante que sempre apareçam nos logs do Render.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
