# Generated by Django 5.2.16 on 2026-08-05 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomacaoComentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Só pra identificar, ex: Sorteio de agosto",
                        max_length=100,
                        verbose_name="Nome da automação",
                    ),
                ),
                (
                    "instagram_media_id",
                    models.CharField(
                        max_length=64, verbose_name="ID do post no Instagram"
                    ),
                ),
                ("link_post", models.URLField(blank=True, verbose_name="Link do post")),
                (
                    "palavras_chave",
                    models.TextField(
                        help_text="Uma palavra-chave por linha. Não diferencia maiúscula/minúscula nem acento.",
                        verbose_name="Palavras-chave",
                    ),
                ),
                (
                    "responder_comentario",
                    models.BooleanField(
                        default=False,
                        verbose_name="Responder o comentário publicamente",
                    ),
                ),
                (
                    "texto_resposta",
                    models.TextField(
                        blank=True, verbose_name="Texto da resposta pública"
                    ),
                ),
                (
                    "enviar_dm",
                    models.BooleanField(
                        default=False, verbose_name="Enviar mensagem direta (DM)"
                    ),
                ),
                ("texto_dm", models.TextField(blank=True, verbose_name="Texto da DM")),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Automação de comentário",
                "verbose_name_plural": "Automações de comentário",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ComentarioProcessado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instagram_comment_id", models.CharField(max_length=64, unique=True)),
                ("instagram_autor_id", models.CharField(blank=True, max_length=64)),
                ("autor_username", models.CharField(blank=True, max_length=150)),
                ("texto_comentario", models.TextField(blank=True)),
                (
                    "palavra_chave_encontrada",
                    models.CharField(blank=True, max_length=100),
                ),
                ("resposta_publica_enviada", models.BooleanField(default=False)),
                ("resposta_publica_erro", models.TextField(blank=True)),
                ("dm_enviada", models.BooleanField(default=False)),
                ("dm_erro", models.TextField(blank=True)),
                ("dm_respondida", models.BooleanField(default=False)),
                ("dm_respondida_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "automacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="automacao_instagram.automacaocomentario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário processado",
                "verbose_name_plural": "Comentários processados",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ContaInstagramConectada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_exibicao",
                    models.CharField(
                        help_text="Ex: @usecashb - só pra identificar a conta nas telas.",
                        max_length=100,
                        verbose_name="Nome de exibição",
                    ),
                ),
                (
                    "instagram_business_account_id",
                    models.CharField(
                        max_length=64, verbose_name="ID da conta comercial do Instagram"
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        help_text="Token de longa duração gerado no painel da Meta pra essa conta.",
                        max_length=512,
                        verbose_name="Access token",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contas_instagram",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta do Instagram conectada",
                "verbose_name_plural": "Contas do Instagram conectadas",
                "ordering": ["nome_exibicao"],
            },
        ),
        migrations.AddField(
            model_name="automacaocomentario",
            name="conta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automacoes",
                to="automacao_instagram.containstagramconectada",
            ),
        ),
    ]
