# Generated by Django 5.2.16 on 2026-08-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automacao_instagram", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containstagramconectada",
            name="instagram_business_account_id",
            field=models.CharField(
                help_text="ID numérico da conta (não é o @usuário) - aparece no Meta Business Suite, em Configurações > Contas > Instagram, ou é retornado pela Graph API.",
                max_length=64,
                verbose_name="ID da conta comercial do Instagram",
            ),
        ),
    ]
