# Generated by Django 5.2.16 on 2026-09-02 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "automacao_instagram",
            "0002_alter_containstagramconectada_instagram_business_account_id",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomacaoStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Só pra identificar, ex: Fone bluetooth 02/09",
                        max_length=100,
                        verbose_name="Nome da automação",
                    ),
                ),
                (
                    "instagram_story_media_id",
                    models.CharField(
                        max_length=64, verbose_name="ID do story no Instagram"
                    ),
                ),
                (
                    "story_permalink",
                    models.URLField(blank=True, verbose_name="Link do story"),
                ),
                (
                    "modo_resposta",
                    models.CharField(
                        choices=[
                            (
                                "link_produto",
                                "Link do produto do story (detectado automaticamente)",
                            ),
                            ("personalizada", "Mensagem personalizada"),
                        ],
                        default="personalizada",
                        max_length=20,
                        verbose_name="O que enviar por DM",
                    ),
                ),
                (
                    "texto_personalizado",
                    models.TextField(
                        blank=True,
                        help_text='Usado quando o modo é "Mensagem personalizada" - ignorado no modo "Link do produto".',
                        verbose_name="Mensagem personalizada",
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automacoes_story",
                        to="automacao_instagram.containstagramconectada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Automação de story",
                "verbose_name_plural": "Automações de story",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="RespostaStoryProcessada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instagram_autor_id", models.CharField(blank=True, max_length=64)),
                ("autor_username", models.CharField(blank=True, max_length=150)),
                ("texto_recebido", models.TextField(blank=True)),
                ("dm_enviada", models.BooleanField(default=False)),
                ("dm_erro", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "automacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="automacao_instagram.automacaostory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta a story processada",
                "verbose_name_plural": "Respostas a stories processadas",
                "ordering": ["-criado_em"],
            },
        ),
    ]
