# Generated by Django 5.2.16 on 2026-08-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="click",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("produto", "Link de produto convertido"),
                    ("vitrine", "Vitrine de ofertas"),
                    ("home", "Página inicial da Shopee"),
                ],
                max_length=10,
            ),
        ),
    ]
