# Generated by Django 5.2.16 on 2026-09-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0004_backfill_item_id_alvo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="click",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("produto", "Link de produto convertido"),
                    ("vitrine", "Vitrine de ofertas"),
                    ("home", "Página inicial da Shopee"),
                    ("story_dm", "Link enviado por DM (resposta a story)"),
                ],
                max_length=10,
            ),
        ),
    ]
