# Generated by Django 5.2.16 on 2026-09-26 01:49

import licencas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventoWebhookKiwify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhook_event_type",
                    models.CharField(blank=True, db_index=True, max_length=60),
                ),
                ("order_status", models.CharField(blank=True, max_length=30)),
                ("subscription_status", models.CharField(blank=True, max_length=30)),
                (
                    "kiwify_subscription_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("corpo_bruto", models.TextField()),
                ("assinatura_valida", models.BooleanField(default=False)),
                ("processado_com_sucesso", models.BooleanField(default=False)),
                ("erro", models.TextField(blank=True)),
                ("recebido_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-recebido_em"],
            },
        ),
        migrations.CreateModel(
            name="Licenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chave",
                    models.CharField(
                        db_index=True,
                        default=licencas.models.gerar_chave,
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("nome", models.CharField(blank=True, max_length=140)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativa", "Ativa"),
                            ("cancelada", "Cancelada"),
                            ("atrasada", "Pagamento atrasado"),
                            ("reembolsada", "Reembolsada"),
                            ("chargeback", "Chargeback"),
                            ("recusada", "Compra recusada"),
                        ],
                        default="ativa",
                        max_length=12,
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        help_text="Texto mostrado pro usuário no app quando a licença não está válida.",
                        max_length=200,
                    ),
                ),
                ("plano", models.CharField(blank=True, max_length=80)),
                (
                    "expira_em",
                    models.DateField(
                        blank=True,
                        help_text="Próxima cobrança prevista pela Kiwify.",
                        null=True,
                    ),
                ),
                (
                    "kiwify_subscription_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "kiwify_customer_email",
                    models.EmailField(
                        blank=True,
                        help_text="Cópia do e-mail no momento da criação, caso o comprador troque o e-mail depois.",
                        max_length=254,
                    ),
                ),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-criada_em"],
            },
        ),
    ]
